### ISSUE TITLE
ライセンス表記とリリースタグを切っていただくことは可能でしょうか？

### ISSUE THREAD

**Issue by kobusan** [tomorrowkey/android-gifview#3]
大変ありがたく使わせていただいてます。
今回アプリでこのOSSを使用したいので、ライセンス表記とリリースタグを切っていただけますでしょうか？
ご検討のほど、よろしくお願いします。

**Comment by tomorrowkey** [comment]
このライブラリはメンテナンスされていませんので、使用をおすすめしません。
Gifアニメーションを再生するにはGlideの使用をおすすめします。 https://github.com/bumptech/glide

**Comment by tomorrowkey** [comment]
一応ライセンス表記は追加しました。

**Comment by kobusan** [comment]
わざわざ対応していただき、ありがとうございます！！！！！！！！
助かりました！！！！
